# roles/software_updates/tasks/main.yml
---

- name: Update repositories
  apt:
    update_cache: yes
  sudo: yes

- name: Upgrade installed packages
  apt:
    name: "*"
    state: latest
  sudo: yes