# roles/software_updates/tasks/main.yml
---

- name: Update repositories
  apt:
    update_cache: yes
  become: yes

- name: Upgrade installed packages
  apt:
    name: "*"
    state: latest
  become: yes