# roles/deploy_vm_template/tasks/main.yml
---
- name: Deploy VM template
  community.vmware.vmware_content_deploy_ovf_template:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validatecerts }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vcenter_folder }}"
    host: "{{ vcenter_host }}"
    resource_pool:
    datastore: "{{ vcenter_datastore }}"
    ovf_template: "{{ vcenter_ovftemplate }}"
    name: "{{ vm_name }}"
